{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.fapolicyd;

  mkValueString =
    v:
    if builtins.isBool v then
      if v then "1" else "0"
    else if builtins.isInt v then
      toString v
    else if builtins.isList v then
      lib.concatStringsSep "," (map mkValueString v)
    else
      toString v;

  confText = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (name: val: "${name} = ${mkValueString val}") cfg.settings
  );

  sortedRuleNames = lib.naturalSort (lib.attrNames finalRules);

  compiledRules =
    if finalRules == { } then
      pkgs.writeText "compiled.rules" "# No rules configured\n"
    else
      pkgs.runCommandLocal "fapolicyd-compiled.rules" { } ''
        echo "## This file is automatically generated from rules.d" > $out
        ${
          lib.concatStringsSep "\n" (
            map (name: ''
              cat ${lib.escapeShellArg (pkgs.writeText name finalRules.${name})} >> $out
            '') sortedRuleNames
          )
        }
        sed -i '/^\s*#/d;/^\s*$/d' $out
      '';

  trustFileContent =
    let
      header = "# AUTOGENERATED FILE VERSION 3\n# This file contains a list of trusted files\n#\n#  FULL PATH        SIZE                             SHA256";
    in
    if cfg.trust == "" then header else "${header}\n${cfg.trust}";

  filterFileContent = lib.concatStringsSep "\n" (
    [
      "+ /"
      " - usr/include/"
      " - usr/share/"
      "  + *.py?"
      "  + *.py"
      "  + */bin/*"
      "  + */libexec/*"
      "  + *.rb"
      "  + *.pl"
      "  + *.stp"
      "  + *.js"
      "  + *.jar"
      "  + *.m4"
      "  + *.php"
      "  + *.pm"
      "  + *.lua"
      "  + *.class"
      "  + *.ts"
      "  + *.tsx"
      "  + *.el"
      "  + *.elc"
      "  + lmod/*/bash"
      " - usr/src/*/"
      "  + */scripts/*"
      "   - *.c"
      "   - *.h"
      "  + */tools/objtool/*"
      " - *.xz"
      " - *.html"
      " - *.json"
      " - *.md"
      " - *.conf"
      " - *.png"
    ]
    ++ cfg.extraFilterRules
  );

  python3Path = "${pkgs.python3.interpreter}";
  ldSoPath = "${pkgs.stdenv.cc.bintools.dynamicLinker}";

  nixosRules = {
    "10-nix-store.rules" = ''
      allow perm=any all : dir=/nix/store/
    '';
    "20-wrappers.rules" = ''
      allow perm=any all : dir=/run/wrappers/
    '';
    "30-patterns.rules" = ''
      deny_audit perm=any pattern=ld_so : all
    '';
    "40-bad-elf.rules" = ''
      deny_audit perm=any all : ftype=application/x-bad-elf
    '';
    "90-deny-execute.rules" = ''
      deny_audit perm=execute all : all
    '';
    "95-allow-open.rules" = ''
      allow perm=open all : all
    '';
  };

  knownLibsRules = {
    "10-languages.rules" = ''
      %languages=application/x-bytecode.ocaml,application/x-bytecode.python,application/java-archive,text/x-java,application/x-java-applet,application/javascript,text/javascript,text/x-awk,text/x-gawk,text/x-lisp,application/x-elc,text/x-lua,text/x-m4,text/x-nftables,text/x-perl,text/x-php,text/x-script.python,text/x-python,text/x-R,text/x-ruby,text/x-script.guile,text/x-tcl,text/x-luatex,text/x-systemtap
    '';
    "30-patterns.rules" = ''
      deny_audit perm=any pattern=ld_so : all
    '';
    "40-bad-elf.rules" = ''
      deny_audit perm=any all : ftype=application/x-bad-elf
    '';
    "41-shared-obj.rules" = ''
      allow perm=open all : ftype=application/x-sharedlib trust=1
      deny_audit perm=open all : ftype=application/x-sharedlib
    '';
    "42-trusted-elf.rules" = ''
      allow perm=execute all : trust=1
    '';
    "70-trusted-lang.rules" = ''
      allow perm=open all : ftype=%languages trust=1
      deny_audit perm=any all : ftype=%languages
    '';
    "72-shell.rules" = ''
      allow perm=any all : ftype=text/x-shellscript
    '';
    "90-deny-execute.rules" = ''
      deny_audit perm=execute all : all
    '';
    "95-allow-open.rules" = ''
      allow perm=open all : all
    '';
  };

  profileRules =
    if cfg.profile == "nixos" then
      nixosRules
    else if cfg.profile == "known-libs" then
      knownLibsRules
    else
      { };

  finalRules = cfg.rules // cfg.extraRules;
in
{
  options.services.fapolicyd = {
    enable = lib.mkEnableOption "fapolicyd, a file access policy daemon for application whitelisting";

    package = lib.mkPackageOption pkgs "fapolicyd" { };

    permissive = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Whether to run in permissive mode (log denials but do not enforce them).
        It is strongly recommended to keep this enabled until the policy
        is verified, as an incorrect policy can deadlock the system.
      '';
    };

    profile = lib.mkOption {
      type = lib.types.enum [
        "nixos"
        "known-libs"
        "custom"
      ];
      default = "nixos";
      description = ''
        Pre-built rule profile for fapolicyd:

        - `nixos`: trusts /nix/store and /run/wrappers, denies all other
          execution. Best for NixOS where the immutable store is the
          source of truth. Does not require a trust database.
        - `known-libs`: upstream known-libs policy. Trusts files in the
          trust database and shared libraries from trusted paths. Requires
          a populated trust database.
        - `custom`: provides no default rules — you must set
          {option}`services.fapolicyd.rules` yourself.
      '';
    };

    settings = lib.mkOption {
      type =
        with lib.types;
        attrsOf (oneOf [
          bool
          int
          str
        ]);
      default = { };
      example = lib.literalExpression ''
        {
          q_size = 800;
          integrity = "size";
        }
      '';
      description = ''
        Configuration for fapolicyd.conf. Keys correspond to the
        configuration options documented in {manpage}`fapolicyd.conf.5`.
        Boolean values are converted to 0/1 automatically.
        The default settings include sensible values for NixOS.
      '';
    };

    rules = lib.mkOption {
      type = with lib.types; attrsOf lines;
      default = profileRules;
      defaultText = lib.literalMD "Generated from `services.fapolicyd.profile`";
      example = lib.literalExpression ''
        {
          "10-nix-store.rules" = '''
            allow perm=any all : dir=/nix/store/
          ''';
          "90-deny-execute.rules" = '''
            deny_audit perm=execute all : all
          ''';
        }
      '';
      description = ''
        Rule files for {file}`/etc/fapolicyd/rules.d/`.
        Attribute names must follow the upstream naming convention
        (e.g. {file}`10-languages.rules`,
        {file}`90-deny-execute.rules`).  Rules are processed in
        natural sort order.  The placeholders
        {var}`services.fapolicyd.python3Path` and
        {var}`services.fapolicyd.ldSoPath` can be referenced in
        custom rules.

        Setting this option entirely overrides the profile's rules.
        To add rules on top of a profile, use
        {option}`services.fapolicyd.extraRules` instead.
      '';
    };

    extraRules = lib.mkOption {
      type = with lib.types; attrsOf lines;
      default = { };
      example = lib.literalExpression ''
        {
          "15-authorized.rules" = '''
            allow perm=any all : dir=/home/user/authorized/
          ''';
        }
      '';
      description = ''
        Extra rule files merged on top of
        {option}`services.fapolicyd.rules`.  Use this to add
        rules without replacing the profile defaults.
      '';
    };

    trust = lib.mkOption {
      type = lib.types.lines;
      default = "";
      example = lib.literalExpression ''
        /nix/store/xxxx-bash-5.2/bin/bash 1234567 abcdef1234567890
      '';
      description = ''
        Content of {file}`/etc/fapolicyd/fapolicyd.trust`.
        Each line should be: path size sha256.
        Use {command}`fapolicyd-cli --file add <path>` on a
        running system to generate entries, then copy them here.
        On NixOS the {file}`/etc/fapolicyd/fapolicyd.trust` file
        is read-only; to add entries declaratively, set this option
        and rebuild.
      '';
    };

    extraFilterRules = lib.mkOption {
      type = with lib.types;
      listOf str;
      default = [ ];
      description = ''
        Extra filter rules appended to
        {file}`/etc/fapolicyd/fapolicyd-filter.conf`.
      '';
    };

    python3Path = lib.mkOption {
      type = lib.types.str;
      default = python3Path;
      defaultText = lib.literalExpression "\${pkgs.python3.interpreter}";
      description = ''
        Path to the Python 3 interpreter.  Used to substitute
        the {var}`%python3_path%` macro in policy rules.
      '';
    };

    ldSoPath = lib.mkOption {
      type = lib.types.str;
      default = ldSoPath;
      defaultText = lib.literalExpression "\${pkgs.stdenv.cc.bintools.dynamicLinker}";
      description = ''
        Path to the dynamic linker (ld.so).  Used to substitute
        the {var}`%ld_so_path%` macro in policy rules.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = finalRules != { };
        message = "fapolicyd requires at least one rule to function. Set services.fapolicyd.rules, services.fapolicyd.extraRules, or use a profile.";
      }
      {
        assertion =
          cfg.permissive == false
          -> lib.any (
            name:
            lib.hasInfix "dir=/nix" (finalRules.${name} or "")
            || lib.hasInfix "trust=1" (finalRules.${name} or "")
          ) (lib.attrNames finalRules);
        message = "fapolicyd in enforcing mode without any trusted paths or /nix/store rules will likely deadlock on NixOS. Either add trust entries, include a dir=/nix/store rule, or keep permissive=true.";
      }
    ];

    users.users.fapolicyd = {
      isSystemUser = true;
      group = "fapolicyd";
      home = "/var/lib/fapolicyd";
      description = "File Access Policy Daemon";
    };

    users.groups.fapolicyd = { };

    services.fapolicyd.settings = lib.mkMerge [
      {
        permissive = cfg.permissive;
        nice_val = 14;
        q_size = 800;
        uid = "fapolicyd";
        gid = "fapolicyd";
        do_stat_report = true;
        detailed_report = true;
        db_max_size = "auto";
        subj_cache_size = 8191;
        obj_cache_size = 8191;
        watch_fs = "ext2,ext3,ext4,tmpfs,xfs,vfat,iso9660,btrfs";
        trust = "file";
        integrity = "none";
        syslog_format = "rule,dec,perm,auid,pid,exe,:,path,ftype,trust";
        rpm_sha256_only = false;
        allow_filesystem_mark = true;
        report_interval = 0;
        reset_strategy = "never";
        timing_collection = "off";
      }
    ];

    environment.etc =
      {
        "fapolicyd/fapolicyd.conf".source = pkgs.writeText "fapolicyd.conf" confText;
        "fapolicyd/compiled.rules".source = compiledRules;
        "fapolicyd/fapolicyd.trust".source = pkgs.writeText "fapolicyd.trust" trustFileContent;
        "fapolicyd/fapolicyd-filter.conf".source =
          pkgs.writeText "fapolicyd-filter.conf" filterFileContent;
      }
      // lib.mapAttrs' (name: content: {
        name = "fapolicyd/rules.d/${name}";
        value.source = pkgs.writeText "fapolicyd-rule-${name}" (
          lib.replaceStrings
            [ "%python3_path%" "%ld_so_path%" ]
            [ cfg.python3Path cfg.ldSoPath ]
            content
        );
      }) finalRules;

    systemd.packages = [ cfg.package ];

    systemd.services.fapolicyd = {
      description = "File Access Policy Daemon";
      wantedBy = [ "multi-user.target" ];
      after = [
        "local-fs.target"
        "systemd-tmpfiles-setup.service"
      ];

      unitConfig.DefaultDependencies = false;

      serviceConfig = {
        Type = "forking";
        PIDFile = "/run/fapolicyd.pid";
        ExecStartPre = [ "" ];
        ExecStart = [ "" "${lib.getExe' cfg.package "fapolicyd"}" ];
        RuntimeDirectory = "fapolicyd";
        RuntimeDirectoryMode = "0770";
        OOMScoreAdjust = -1000;
        Restart = "on-abnormal";
      };
    };

    systemd.tmpfiles.settings."fapolicyd" = {
      "/var/lib/fapolicyd".d = {
        mode = "0770";
        user = "root";
        group = "fapolicyd";
      };
      "/etc/fapolicyd".d = {
        mode = "0755";
        user = "root";
        group = "fapolicyd";
      };
    };

    environment.systemPackages = [ cfg.package ];
  };
}